#!/usr/bin/env python3
"""
Generate test cases for the JS/TS code-formatter harbor task from Prettier's
snapshot files.

Parses __snapshots__/format.test.js.snap files from Prettier's test suite and
extracts input/output pairs for default-option configurations. Selects ~250
of the best cases that maximize coverage across syntax categories.

Creates:
- Original cases in environment/formatter/tests/cases/ (visible to agent)
- Variant cases in tests/hidden_cases/ (hidden, for verification only)

Hidden variants are generated by modifying string/comment/number tokens in
the original input, then running Prettier on the variant to get expected output.
"""

import os
import sys
import re
import json
import subprocess
import shutil
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
ENV_CASES_DIR = BASE_DIR / "environment" / "formatter" / "tests" / "cases"
HIDDEN_CASES_DIR = BASE_DIR / "tests" / "hidden_cases"
PRETTIER_REPO = Path("/tmp/prettier-repo")
PRETTIER_TESTS = PRETTIER_REPO / "tests" / "format"

SIBLING_TASK = BASE_DIR.parent / (
    "code-formatter-js-js"
    if "python" in BASE_DIR.name
    else "code-formatter-js-python"
)

TARGET_TOTAL = 250
MAX_PER_CATEGORY = 1

SKIP_CATEGORIES = {
    "_errors_", "cursor", "range", "bom", "eol", "end-of-line",
    "ignore", "object-property-ignore", "prettier-ignore",
    "invalid-code", "performance",
    "no-semi", "no-semi-babylon-extensions", "nosemi",
    "tab-width", "bracket-spacing",
    "arrows-bind", "bind-expressions",
    "pipeline-operator", "comments-pipeline-own-line",
    "partial-application", "module-blocks",
    "async-do-expressions", "throw_expressions",
    "v8_intrinsic",
    "discard-binding", "deferred-import-evaluation",
    "destructuring-ignore", "destructuring-private-fields",
    "compiler", "conformance",
    "edge-cases", "error-recovery",
    "typescript-babel-only", "typescript-only",
    "webhost",
    "deprecated-jsx-bracket-same-line-option",
    "angular-component-examples",
    "multiparser-css", "multiparser-graphql", "multiparser-html",
    "multiparser-markdown", "multiparser-text", "multiparser-comments",
    "multiparser-invalid",
    "embed", "fbt", "lwc",
    "do", "source-phase-imports", "import-assertions",
    "optional-chaining-assignment", "non-strict",
    "sloppy-mode", "return-outside-function",
    "line-suffix-boundary",
    "babel-plugins",
    "template-align",
    "require-amd",
    "d-ts-files",
    "property-signature",
    "comments-closure-typecast",
    "import-meta", "new-target", "module-string-names",
    "line", "empty",
    "long-type-parameters",
    "expression_statement", "binary_math",
    "require",
    "single-attribute-per-line",
    "object-colon-bug",
    # Niche subcategories
    "semi", "comments",
    "flow-repo",
    "numeric-separators", "literal-numeric-separator",
    "shebang", "label",
    "identifier", "in",
    "object-prop-break-in",
    "sequence-break", "sequence-expression",
    "reserved-word", "non-null",
    "top-level-await",
    "type-arguments-bit-shift-left-like",
    "type-member-get-set",
    "type-only-module-specifiers",
    "type-parameters-arguments",
    "typeof-this",
    "optional-variance",
    "private-fields-in-in",
    "key-remapping-in-mapped-types",
    "infer-extends",
    "instantiation-expression",
    "intrinsic", "symbol", "never", "unknown",
    "unique-symbol",
    "abstract-construct-types",
    "abstract-property",
    "override-modifiers",
    "decorator-auto-accessors",
    "decorators-ts",
    "decorators-export",
    "import-require",
    "import-type",
}

# Categories where we want more files (core formatting concepts)
HIGH_PRIORITY_CATEGORIES = {
    "arrays", "objects", "arrows", "function", "classes",
    "comments", "ternaries", "conditional", "method-chain",
    "break-calls", "trailing-comma", "destructuring",
    "template-literals", "assignment",
    "interface", "enum", "type-alias", "generic",
    "conditional-types", "union", "tuple",
    "jsx", "text-wrap",
    "import", "export",
}


def clone_prettier():
    """Clone Prettier's test suite using sparse checkout."""
    if PRETTIER_REPO.exists():
        print("  Prettier repo already exists, reusing.")
        return
    print("  Cloning Prettier repository (sparse)...")
    subprocess.run(
        [
            "git", "clone", "--filter=blob:none", "--sparse",
            "https://github.com/prettier/prettier.git",
            str(PRETTIER_REPO),
        ],
        check=True, capture_output=True,
    )
    subprocess.run(
        ["git", "sparse-checkout", "set", "tests/format"],
        cwd=str(PRETTIER_REPO), check=True, capture_output=True,
    )
    print("  Done cloning.")


def install_prettier():
    """Install Prettier globally for generating variant expected outputs."""
    try:
        result = subprocess.run(
            ["prettier", "--version"], capture_output=True, text=True,
        )
        if result.returncode == 0:
            print(f"  Prettier already installed: v{result.stdout.strip()}")
            return
    except FileNotFoundError:
        pass
    print("  Installing Prettier...")
    subprocess.run(
        ["sudo", "npm", "install", "-g", "prettier"],
        check=True, capture_output=True,
    )
    print("  Done installing Prettier.")


def unescape_snapshot(content):
    """Unescape Jest snapshot template literal content."""
    result = []
    i = 0
    while i < len(content):
        if content[i] == '\\' and i + 1 < len(content):
            nxt = content[i + 1]
            if nxt in ('`', '$'):
                result.append(nxt)
                i += 2
            elif nxt == '\\':
                result.append('\\')
                i += 2
            else:
                result.append(content[i])
                i += 1
        else:
            result.append(content[i])
            i += 1
    return ''.join(result)


INPUT_SEP = "=" * 37 + "input" + "=" * 38
OUTPUT_SEP = "=" * 37 + "output" + "=" * 37
FINAL_SEP = "=" * 80

ENTRY_RE = re.compile(
    r'exports\[`(.*?)`\]\s*=\s*`\n(.*?)\n' + FINAL_SEP + r'\n`;\n',
    re.DOTALL,
)


def parse_snapshot_file(filepath):
    """Parse a Jest snapshot file and yield (key, input, output) tuples."""
    content = filepath.read_text(encoding="utf-8")

    for match in ENTRY_RE.finditer(content):
        key = match.group(1)
        body = match.group(2)

        input_idx = body.find(INPUT_SEP)
        output_idx = body.find(OUTPUT_SEP)
        if input_idx == -1 or output_idx == -1:
            continue

        input_text = body[input_idx + len(INPUT_SEP) + 1:output_idx].rstrip('\n') + '\n'
        output_text = body[output_idx + len(OUTPUT_SEP) + 1:]
        if not output_text.endswith('\n'):
            output_text += '\n'

        yield key, unescape_snapshot(input_text), unescape_snapshot(output_text)


KEY_WITH_OPTS_RE = re.compile(r'(.+?)\s+-\s+(\{.*\})\s+format\s+\d+')
KEY_PLAIN_RE = re.compile(r'(.+?)\s+format\s+\d+')


def extract_key_info(key):
    """Extract filename and options from a snapshot key."""
    m = KEY_WITH_OPTS_RE.match(key)
    if m:
        try:
            return m.group(1).strip(), json.loads(m.group(2))
        except json.JSONDecodeError:
            return m.group(1).strip(), {}
    m = KEY_PLAIN_RE.match(key)
    if m:
        return m.group(1).strip(), {}
    return key, {}


NON_DEFAULT_CHECKS = {
    "arrowParens": lambda v: v != "always",
    "semi": lambda v: v is not True and str(v).lower() != "true",
    "singleQuote": lambda v: v is not False and str(v).lower() != "false",
    "tabWidth": lambda v: v != 2,
    "useTabs": lambda v: v is not False and str(v).lower() != "false",
    "printWidth": lambda v: v != 80,
    "trailingComma": lambda v: v not in ("all",),
    "bracketSpacing": lambda v: str(v).lower() != "true" and v is not True,
    "bracketSameLine": lambda v: str(v).lower() != "false" and v is not False,
    "jsxSingleQuote": lambda v: str(v).lower() != "false" and v is not False,
    "quoteProps": lambda v: v != "as-needed",
    "htmlWhitespaceSensitivity": lambda _: True,
    "proseWrap": lambda _: True,
    "endOfLine": lambda _: True,
}


def has_non_default_options(options):
    for k, check in NON_DEFAULT_CHECKS.items():
        if k in options and check(options[k]):
            return True
    return False


def detect_extension(category_path, filename):
    if any(filename.endswith(e) for e in ('.ts', '.tsx', '.js', '.jsx')):
        return filename.rsplit('.', 1)[-1]
    parts = str(category_path).split("/tests/format/")
    if len(parts) > 1:
        top_dir = parts[1].split("/")[0]
        if top_dir == "typescript":
            return "ts"
    return "js"


def score_case(input_text, output_text):
    """Score a test case by how interesting its formatting is.

    Higher = more interesting. Prefer cases where:
    - input != output (actual formatting happens)
    - moderate length (not trivially short, not excessively long)
    - diverse syntax (more different token types)
    """
    score = 0
    if input_text.strip() != output_text.strip():
        score += 50

    length = len(input_text)
    if 100 < length < 2000:
        score += 30
    elif 50 < length <= 100:
        score += 15
    elif 2000 <= length < 5000:
        score += 20
    elif length >= 5000:
        score += 5

    for pattern in ['=>', 'class ', 'interface ', 'function ', 'import ',
                    'export ', 'async ', 'await ', 'for ', 'if ', 'switch ',
                    '...', '?.', '??', '`', '// ', '/*', '<', 'type ',
                    'enum ', 'extends ', 'implements ', 'generic',
                    'const ', 'let ', 'var ']:
        if pattern in input_text:
            score += 2

    return score


def safe_vowel_swap(text):
    vowel_map = {
        "a": "e", "e": "i", "i": "o", "o": "u", "u": "a",
        "A": "E", "E": "I", "I": "O", "O": "U", "U": "A",
    }
    result = []
    i = 0
    while i < len(text):
        if text[i] == "\\" and i + 1 < len(text):
            result.append(text[i])
            result.append(text[i + 1])
            i += 2
        else:
            result.append(vowel_map.get(text[i], text[i]))
            i += 1
    return "".join(result)


def create_variant_input(source):
    """Create a variant of JS/TS source by modifying strings, comments, numbers."""
    modified = source

    modified = re.sub(
        r'(")((?:[^"\\]|\\.)*?)(")',
        lambda m: m.group(1) + safe_vowel_swap(m.group(2)) + m.group(3),
        modified,
    )

    modified = re.sub(
        r"(')((?:[^'\\]|\\.)*?)(')",
        lambda m: m.group(1) + safe_vowel_swap(m.group(2)) + m.group(3),
        modified,
    )

    PRESERVE_COMMENT = ("prettier-ignore", "@ts-", "eslint", "type:", "noqa",
                        "TODO", "FIXME", "NOTE", "!", "@")

    def modify_line_comment(m):
        prefix, text = m.group(1), m.group(2)
        if any(p in text for p in PRESERVE_COMMENT):
            return m.group(0)
        return prefix + safe_vowel_swap(text)

    modified = re.sub(r'(//\s?)(.*?)$', modify_line_comment, modified, flags=re.MULTILINE)

    def modify_integer(m):
        s = m.group(2)
        if s.startswith(('0x', '0X', '0o', '0O', '0b', '0B')):
            return m.group(0)
        try:
            if '.' in s or 'e' in s.lower():
                return m.group(0)
            return m.group(1) + str(int(s.replace('_', '')) + 7)
        except ValueError:
            return m.group(0)

    modified = re.sub(r'(\b)(\d[\d_]*)\b', modify_integer, modified)

    if modified == source:
        modified = "// Variant test file\n" + source
    return modified


def format_with_prettier(source, filepath):
    ext = filepath.rsplit('.', 1)[-1] if '.' in filepath else 'js'
    parser = "typescript" if ext in ("ts", "tsx") else "babel"
    try:
        result = subprocess.run(
            ["prettier", "--parser", parser, "--stdin-filepath", filepath],
            input=source, capture_output=True, text=True, timeout=30,
        )
        if result.returncode == 0:
            return result.stdout
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass
    return None


def collect_all_eligible_cases():
    """Walk Prettier test dirs and collect ALL eligible cases from snapshots."""
    cases = []
    seen = set()

    for lang_dir in ["js", "jsx", "typescript"]:
        lang_path = PRETTIER_TESTS / lang_dir
        if not lang_path.exists():
            continue

        for root, dirs, _files in os.walk(lang_path):
            root_path = Path(root)
            category = root_path.name
            if category in SKIP_CATEGORIES:
                dirs[:] = [d for d in dirs if d not in SKIP_CATEGORIES]
                continue

            snap_dir = root_path / "__snapshots__"
            if not snap_dir.exists():
                continue

            for snap_file in sorted(snap_dir.iterdir()):
                if not snap_file.name.endswith(".snap"):
                    continue

                best_per_file = {}
                for key, inp, out in parse_snapshot_file(snap_file):
                    filename, options = extract_key_info(key)
                    if has_non_default_options(options):
                        continue
                    if not inp.strip() or not out.strip() or len(inp) < 15:
                        continue

                    file_key = f"{lang_dir}/{category}/{filename}"
                    if file_key in seen:
                        continue

                    pref = 0 if not options else 1
                    ext = detect_extension(root_path, filename)
                    sc = score_case(inp, out)

                    if file_key not in best_per_file or pref < best_per_file[file_key][0]:
                        best_per_file[file_key] = (
                            pref, sc, file_key, inp, out,
                            ext, lang_dir, category, filename,
                        )

                for file_key, entry in best_per_file.items():
                    seen.add(file_key)
                    cases.append(entry)

    return cases


def select_best_cases(all_cases, target=TARGET_TOTAL):
    """Select the best cases ensuring broad category coverage."""
    by_group = {}
    for entry in all_cases:
        _, sc, file_key, inp, out, ext, lang_dir, category, filename = entry
        group_key = (lang_dir, category)
        by_group.setdefault(group_key, []).append(entry)

    for group_key in by_group:
        by_group[group_key].sort(key=lambda e: e[1], reverse=True)

    selected = []

    for group_key, entries in sorted(by_group.items()):
        lang_dir, category = group_key
        limit = MAX_PER_CATEGORY
        if category in HIGH_PRIORITY_CATEGORIES:
            limit = min(len(entries), 2)
        for entry in entries[:limit]:
            selected.append(entry)

    if len(selected) > target:
        selected.sort(key=lambda e: e[1], reverse=True)

        keep = set()
        for group_key, entries in by_group.items():
            if entries:
                keep.add(entries[0][2])

        final = [e for e in selected if e[2] in keep]
        remaining = [e for e in selected if e[2] not in keep]
        remaining.sort(key=lambda e: e[1], reverse=True)
        final.extend(remaining[:target - len(final)])
        selected = final

    selected.sort(key=lambda e: (e[6], e[7], e[8]))

    print(f"  Selected {len(selected)} cases from {len(by_group)} categories.")
    lang_counts = {}
    for e in selected:
        lang_counts[e[6]] = lang_counts.get(e[6], 0) + 1
    for lang, count in sorted(lang_counts.items()):
        print(f"    {lang}: {count} cases")

    return selected


def main():
    print("=" * 60)
    print("  JS/TS Code Formatter Test Case Generator")
    print("=" * 60)

    print("\nStep 1: Cloning Prettier repository...")
    clone_prettier()

    print("\nStep 2: Installing Prettier...")
    install_prettier()

    print("\nStep 3: Collecting eligible cases from snapshots...")
    all_cases = collect_all_eligible_cases()
    print(f"  Found {len(all_cases)} total eligible cases.")

    print("\nStep 4: Selecting best cases for broad coverage...")
    selected = select_best_cases(all_cases)

    if ENV_CASES_DIR.exists():
        shutil.rmtree(ENV_CASES_DIR)
    if HIDDEN_CASES_DIR.exists():
        shutil.rmtree(HIDDEN_CASES_DIR)
    ENV_CASES_DIR.mkdir(parents=True, exist_ok=True)
    HIDDEN_CASES_DIR.mkdir(parents=True, exist_ok=True)

    print(f"\nStep 5: Writing {len(selected)} test cases...")
    case_num = 0
    case_map = {}
    errors = []

    for _pref, _sc, file_key, input_text, output_text, ext, lang_dir, category, filename in selected:
        case_num += 1
        case_name = f"case_{case_num:03d}"

        case_dir = ENV_CASES_DIR / case_name
        case_dir.mkdir(parents=True, exist_ok=True)
        (case_dir / f"input.{ext}").write_text(input_text, encoding="utf-8")
        (case_dir / f"expected_output.{ext}").write_text(output_text, encoding="utf-8")

        variant_input = create_variant_input(input_text)
        variant_expected = format_with_prettier(variant_input, f"variant.{ext}")

        if variant_expected is None:
            variant_input = "// Variant test file\n" + input_text
            variant_expected = format_with_prettier(variant_input, f"variant.{ext}")

        if variant_expected is None:
            errors.append((filename, "Prettier failed on variant"))
            variant_input = input_text
            variant_expected = output_text

        hidden_dir = HIDDEN_CASES_DIR / case_name
        hidden_dir.mkdir(parents=True, exist_ok=True)
        (hidden_dir / f"input.{ext}").write_text(variant_input, encoding="utf-8")
        (hidden_dir / f"expected_output.{ext}").write_text(variant_expected, encoding="utf-8")

        case_map[case_name] = {
            "source": file_key,
            "language": lang_dir,
            "category": category,
            "filename": filename,
            "extension": ext,
        }

        if case_num % 25 == 0:
            print(f"    ... {case_num}/{len(selected)} cases written")

    mapping_file = BASE_DIR / "tests" / "case_mapping.json"
    with open(mapping_file, "w") as f:
        json.dump(case_map, f, indent=2)

    if SIBLING_TASK.exists():
        print(f"\nStep 6: Copying cases to sibling task ({SIBLING_TASK.name})...")
        sibling_cases = SIBLING_TASK / "environment" / "formatter" / "tests" / "cases"
        sibling_hidden = SIBLING_TASK / "tests" / "hidden_cases"

        if sibling_cases.exists():
            shutil.rmtree(sibling_cases)
        if sibling_hidden.exists():
            shutil.rmtree(sibling_hidden)

        shutil.copytree(ENV_CASES_DIR, sibling_cases)
        shutil.copytree(HIDDEN_CASES_DIR, sibling_hidden)
        shutil.copy2(mapping_file, SIBLING_TASK / "tests" / "case_mapping.json")
        print("  Done copying.")

    print("\n" + "=" * 60)
    print("  Summary")
    print("=" * 60)
    print(f"  Total cases created:    {case_num}")
    print(f"  Variant errors:         {len(errors)}")
    print(f"  Original cases dir:     {ENV_CASES_DIR}")
    print(f"  Hidden cases dir:       {HIDDEN_CASES_DIR}")
    print(f"  Case mapping:           {mapping_file}")

    if errors:
        print(f"\n  Variant errors (fallback to original):")
        for fn, err in errors[:20]:
            print(f"    {fn}: {err}")

    print("\n" + "=" * 60)
    print("  Done!")
    print("=" * 60)
    return case_num


if __name__ == "__main__":
    num_cases = main()
    sys.exit(0 if num_cases > 0 else 1)
