#!/usr/bin/env python3
"""
Generate test cases for the C code-formatter harbor task from clang-format output.

Creates:
- Original cases in environment/formatter/tests/cases/ (visible to agent)
- Variant cases in tests/hidden_cases/ (hidden, for verification only)

Hidden variants are generated by modifying string/number tokens in the
original input, then running clang-format on the variant to get expected output.
"""

import os
import sys
import re
import json
import subprocess
import shutil
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
ENV_CASES_DIR = BASE_DIR / "environment" / "formatter" / "tests" / "cases"
HIDDEN_CASES_DIR = BASE_DIR / "tests" / "hidden_cases"

TARGET_TOTAL = 200


def install_clang_format():
    """Ensure clang-format is available."""
    try:
        result = subprocess.run(
            ["clang-format", "--version"], capture_output=True, text=True,
        )
        print(f"  clang-format available: {result.stdout.strip()}")
    except FileNotFoundError:
        print("  ERROR: clang-format not found. Install clang-format first.")
        sys.exit(1)


def collect_c_files():
    """Collect C source files from system and common locations."""
    candidates = []

    search_dirs = [
        "/usr/include",
        "/usr/local/include",
    ]

    # Also look for C projects in common locations
    home = os.path.expanduser("~")
    extra_dirs = [
        os.path.join(home, "projects"),
        os.path.join(home, "src"),
        "/tmp",
    ]
    search_dirs.extend(extra_dirs)

    for search_dir in search_dirs:
        if not os.path.isdir(search_dir):
            continue
        for root, dirs, files in os.walk(search_dir):
            dirs[:] = [d for d in dirs if d not in (".git", "node_modules", "__pycache__")]
            for f in files:
                if f.endswith((".c", ".h")) and not f.startswith("test"):
                    full = os.path.join(root, f)
                    try:
                        size = os.path.getsize(full)
                        if 200 < size < 8000:
                            candidates.append(full)
                    except OSError:
                        pass
                    if len(candidates) > 3000:
                        return candidates

    return candidates


def score_file(filepath):
    """Score a C file by how interesting its formatting is."""
    try:
        with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
            source = f.read()
    except (IOError):
        return 0

    score = 0
    patterns = [
        "struct ", "enum ", "typedef ", "union ",
        "if (", "else {", "for (", "while (", "switch (", "case ",
        "return ", "void ", "int ", "char ", "const ", "static ",
        "#include", "#define", "#ifdef", "#pragma", "#if ",
        "sizeof(", "malloc(", "free(", "printf(",
        "->", "/*", "//", "...", "volatile", "extern",
        "inline", "__attribute__", "_Bool", "_Alignof",
    ]
    for p in patterns:
        if p in source:
            score += 2

    # Prefer files with actual formatting issues
    lines = source.split("\n")
    long_lines = sum(1 for l in lines if len(l) > 80)
    if long_lines > 0:
        score += min(long_lines * 3, 15)

    length = len(source)
    if 500 < length < 3000:
        score += 20
    elif 200 <= length <= 500:
        score += 10
    elif 3000 <= length < 6000:
        score += 15

    return score


def format_with_clang_format(source):
    """Format C source code with clang-format."""
    try:
        result = subprocess.run(
            ["clang-format", "--style=LLVM"],
            input=source, capture_output=True, text=True, timeout=30,
        )
        if result.returncode == 0:
            return result.stdout
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass
    return None


def create_variant_input(source):
    """Create a variant of C source by modifying strings, comments, numbers."""
    modified = source

    # Modify string literals
    modified = re.sub(
        r'(")((?:[^"\\]|\\.)*?)(")',
        lambda m: m.group(1) + m.group(2).replace("a", "e").replace("e", "i").replace("i", "o").replace("o", "u").replace("u", "a") + m.group(3),
        modified,
    )

    # Modify char literals
    modified = re.sub(
        r"(')((?:[^'\\]|\\.)*?)(')",
        lambda m: m.group(1) + m.group(2).replace("a", "e").replace("e", "i").replace("i", "o") + m.group(3),
        modified,
    )

    # Modify line comments
    PRESERVE_COMMENT = ("TODO", "FIXME", "NOTE", "HACK", "XXX", "NOLINT", "noqa")

    def modify_line_comment(m):
        prefix, text = m.group(1), m.group(2)
        if any(p in text for p in PRESERVE_COMMENT):
            return m.group(0)
        return prefix + text.replace("a", "e").replace("e", "i").replace("i", "o")

    modified = re.sub(r'(//\s?)(.*?)$', modify_line_comment, modified, flags=re.MULTILINE)

    # Modify integer literals
    def modify_integer(m):
        s = m.group(2)
        if s.startswith(('0x', '0X', '0o', '0O', '0b', '0B')):
            return m.group(0)
        try:
            if '.' in s or 'e' in s.lower():
                return m.group(0)
            return m.group(1) + str(int(s) + 7)
        except ValueError:
            return m.group(0)

    modified = re.sub(r'(\b)(\d+)\b', modify_integer, modified)

    if modified == source:
        modified = "// Variant test file\n" + source
    return modified


def main():
    print("=" * 60)
    print("  C Code Formatter Test Case Generator")
    print("=" * 60)

    print("\nStep 1: Checking clang-format availability...")
    install_clang_format()

    print("\nStep 2: Collecting C source files...")
    c_files = collect_c_files()
    print(f"  Found {len(c_files)} candidate files.")

    if len(c_files) < 50:
        print("  WARNING: Few C files found. Results may be limited.")

    print("\nStep 3: Scoring and selecting files...")
    scored = [(score_file(f), f) for f in c_files]
    scored.sort(key=lambda x: x[0], reverse=True)
    selected_files = scored[:TARGET_TOTAL * 2]

    print(f"\nStep 4: Generating test cases (target: {TARGET_TOTAL})...")
    if ENV_CASES_DIR.exists():
        shutil.rmtree(ENV_CASES_DIR)
    if HIDDEN_CASES_DIR.exists():
        shutil.rmtree(HIDDEN_CASES_DIR)
    ENV_CASES_DIR.mkdir(parents=True, exist_ok=True)
    HIDDEN_CASES_DIR.mkdir(parents=True, exist_ok=True)

    case_num = 0
    case_map = {}
    errors = []

    for score, filepath in selected_files:
        if case_num >= TARGET_TOTAL:
            break

        try:
            with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
                source = f.read()
        except (IOError):
            continue

        formatted = format_with_clang_format(source)
        if formatted is None:
            continue

        case_num += 1
        case_name = f"case_{case_num:03d}"

        # Write original case
        case_dir = ENV_CASES_DIR / case_name
        case_dir.mkdir(parents=True, exist_ok=True)
        (case_dir / "input.c").write_text(source, encoding="utf-8")
        (case_dir / "expected_output.c").write_text(formatted, encoding="utf-8")

        # Generate hidden variant
        variant_input = create_variant_input(source)
        variant_expected = format_with_clang_format(variant_input)

        if variant_expected is None:
            variant_input = "// Variant test file\n" + source
            variant_expected = format_with_clang_format(variant_input)

        if variant_expected is None:
            errors.append((filepath, "clang-format failed on variant"))
            variant_input = source
            variant_expected = formatted

        hidden_dir = HIDDEN_CASES_DIR / case_name
        hidden_dir.mkdir(parents=True, exist_ok=True)
        (hidden_dir / "input.c").write_text(variant_input, encoding="utf-8")
        (hidden_dir / "expected_output.c").write_text(variant_expected, encoding="utf-8")

        case_map[case_name] = {
            "source": filepath,
            "language": "c",
        }

        if case_num % 25 == 0:
            print(f"    ... {case_num}/{TARGET_TOTAL} cases written")

    mapping_file = BASE_DIR / "tests" / "case_mapping.json"
    with open(mapping_file, "w") as f:
        json.dump(case_map, f, indent=2)

    print("\n" + "=" * 60)
    print("  Summary")
    print("=" * 60)
    print(f"  Total cases created:    {case_num}")
    print(f"  Variant errors:         {len(errors)}")
    print(f"  Original cases dir:     {ENV_CASES_DIR}")
    print(f"  Hidden cases dir:       {HIDDEN_CASES_DIR}")
    print(f"  Case mapping:           {mapping_file}")

    if errors:
        print(f"\n  Variant errors (fallback to original):")
        for fn, err in errors[:20]:
            print(f"    {fn}: {err}")

    print("\n" + "=" * 60)
    print("  Done!")
    print("=" * 60)
    return case_num


if __name__ == "__main__":
    num_cases = main()
    sys.exit(0 if num_cases > 0 else 1)
