#!/usr/bin/env python3
"""
Generate test cases for the Rust code-formatter harbor task from rustfmt output.

Creates:
- Original cases in environment/formatter/tests/cases/ (visible to agent)
- Variant cases in tests/hidden_cases/ (hidden, for verification only)

Hidden variants are generated by modifying string/number tokens in the
original input, then running rustfmt on the variant to get expected output.
"""

import os
import sys
import re
import json
import subprocess
import shutil
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
ENV_CASES_DIR = BASE_DIR / "environment" / "formatter" / "tests" / "cases"
HIDDEN_CASES_DIR = BASE_DIR / "tests" / "hidden_cases"

TARGET_TOTAL = 200


def install_rustfmt():
    """Ensure rustfmt is available."""
    try:
        result = subprocess.run(
            ["rustfmt", "--version"], capture_output=True, text=True,
        )
        print(f"  rustfmt available: {result.stdout.strip()}")
    except FileNotFoundError:
        print("  ERROR: rustfmt not found. Install Rust first.")
        sys.exit(1)


def collect_rust_files():
    """Collect Rust source files from standard library and popular crates."""
    candidates = []

    # Look in common locations
    rustup_home = os.environ.get("RUSTUP_HOME", os.path.expanduser("~/.rustup"))
    cargo_home = os.environ.get("CARGO_HOME", os.path.expanduser("~/.cargo"))

    # Standard library source
    toolchains_dir = os.path.join(rustup_home, "toolchains")
    if os.path.isdir(toolchains_dir):
        for toolchain in os.listdir(toolchains_dir):
            lib_src = os.path.join(toolchains_dir, toolchain, "lib/rustlib/src/rust/library")
            if os.path.isdir(lib_src):
                for root, dirs, files in os.walk(lib_src):
                    dirs[:] = [d for d in dirs if d not in ("tests", "test", "examples")]
                    for f in files:
                        if f.endswith(".rs") and not f.endswith("_test.rs"):
                            full = os.path.join(root, f)
                            size = os.path.getsize(full)
                            if 200 < size < 8000:
                                candidates.append(full)

    # Registry sources (downloaded crates)
    registry_src = os.path.join(cargo_home, "registry/src")
    if os.path.isdir(registry_src):
        for registry in os.listdir(registry_src):
            reg_path = os.path.join(registry_src, registry)
            if os.path.isdir(reg_path):
                for crate_dir in os.listdir(reg_path):
                    crate_path = os.path.join(reg_path, crate_dir)
                    if os.path.isdir(crate_path):
                        for root, dirs, files in os.walk(crate_path):
                            dirs[:] = [d for d in dirs if d not in ("tests", "test", "examples", "benches")]
                            for f in files:
                                if f.endswith(".rs"):
                                    full = os.path.join(root, f)
                                    size = os.path.getsize(full)
                                    if 200 < size < 8000:
                                        candidates.append(full)
                                    if len(candidates) > 2000:
                                        return candidates

    return candidates


def score_file(filepath):
    """Score a Rust file by how interesting its formatting is."""
    try:
        with open(filepath, "r") as f:
            source = f.read()
    except (UnicodeDecodeError, IOError):
        return 0

    score = 0
    patterns = [
        "fn ", "struct ", "enum ", "impl ", "trait ", "pub ",
        "async ", "await", "match ", "if let", "while let",
        "macro_rules!", "#[derive(", "#[cfg(", "mod ", "use ",
        "where ", "for<", "dyn ", "Box<", "Vec<", "Option<", "Result<",
        "->", "=>", "...", "&mut", "&self", "self.", "Self::",
        "unsafe ", "extern ", "const ", "static ", "type ",
        "println!", "format!", "vec!", "Some(", "None",
    ]
    for p in patterns:
        if p in source:
            score += 2

    length = len(source)
    if 500 < length < 3000:
        score += 20
    elif 200 <= length <= 500:
        score += 10
    elif 3000 <= length < 6000:
        score += 15

    return score


def format_with_rustfmt(source):
    """Format Rust source code with rustfmt."""
    try:
        result = subprocess.run(
            ["rustfmt"],
            input=source, capture_output=True, text=True, timeout=30,
        )
        if result.returncode == 0:
            return result.stdout
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass
    return None


def create_variant_input(source):
    """Create a variant of Rust source by modifying strings, comments, numbers."""
    modified = source

    # Modify string literals
    modified = re.sub(
        r'(")((?:[^"\\]|\\.)*?)(")',
        lambda m: m.group(1) + m.group(2).replace("a", "e").replace("e", "i").replace("i", "o").replace("o", "u").replace("u", "a") + m.group(3),
        modified,
    )

    # Modify raw strings
    def modify_raw_string(m):
        hashes = m.group(1)
        content = m.group(2)
        return hashes + content.replace("a", "e").replace("e", "i").replace("i", "o") + hashes

    modified = re.sub(r'r(#*)"([^"]*)"\1', modify_raw_string, modified)

    # Modify line comments
    PRESERVE_COMMENT = ("TODO", "FIXME", "NOTE", "SAFETY", "UNSAFETY", "clippy", "rustfmt", "allow(", "deny(", "warn(")

    def modify_line_comment(m):
        prefix, text = m.group(1), m.group(2)
        if any(p in text for p in PRESERVE_COMMENT):
            return m.group(0)
        return prefix + text.replace("a", "e").replace("e", "i").replace("i", "o")

    modified = re.sub(r'(//\s?)(.*?)$', modify_line_comment, modified, flags=re.MULTILINE)

    # Modify integer literals
    def modify_integer(m):
        s = m.group(2)
        if s.startswith(('0x', '0X', '0o', '0O', '0b', '0B')):
            return m.group(0)
        try:
            if '.' in s or 'e' in s.lower():
                return m.group(0)
            # Remove underscores for parsing
            clean = s.replace('_', '')
            return m.group(1) + str(int(clean) + 7).replace(s, str(int(clean) + 7))
        except ValueError:
            return m.group(0)

    modified = re.sub(r'(\b)(\d[\d_]*)\b', modify_integer, modified)

    if modified == source:
        modified = "// Variant test file\n" + source
    return modified


def main():
    print("=" * 60)
    print("  Rust Code Formatter Test Case Generator")
    print("=" * 60)

    print("\nStep 1: Checking rustfmt availability...")
    install_rustfmt()

    print("\nStep 2: Collecting Rust source files...")
    rust_files = collect_rust_files()
    print(f"  Found {len(rust_files)} candidate files.")

    if len(rust_files) < 50:
        print("  WARNING: Few Rust files found. Results may be limited.")

    print("\nStep 3: Scoring and selecting files...")
    scored = [(score_file(f), f) for f in rust_files]
    scored.sort(key=lambda x: x[0], reverse=True)
    selected_files = scored[:TARGET_TOTAL * 2]

    print(f"\nStep 4: Generating test cases (target: {TARGET_TOTAL})...")
    if ENV_CASES_DIR.exists():
        shutil.rmtree(ENV_CASES_DIR)
    if HIDDEN_CASES_DIR.exists():
        shutil.rmtree(HIDDEN_CASES_DIR)
    ENV_CASES_DIR.mkdir(parents=True, exist_ok=True)
    HIDDEN_CASES_DIR.mkdir(parents=True, exist_ok=True)

    case_num = 0
    case_map = {}
    errors = []

    for score, filepath in selected_files:
        if case_num >= TARGET_TOTAL:
            break

        try:
            with open(filepath, "r") as f:
                source = f.read()
        except (UnicodeDecodeError, IOError):
            continue

        formatted = format_with_rustfmt(source)
        if formatted is None:
            continue

        case_num += 1
        case_name = f"case_{case_num:03d}"

        # Write original case
        case_dir = ENV_CASES_DIR / case_name
        case_dir.mkdir(parents=True, exist_ok=True)
        (case_dir / "input.rs").write_text(source, encoding="utf-8")
        (case_dir / "expected_output.rs").write_text(formatted, encoding="utf-8")

        # Generate hidden variant
        variant_input = create_variant_input(source)
        variant_expected = format_with_rustfmt(variant_input)

        if variant_expected is None:
            variant_input = "// Variant test file\n" + source
            variant_expected = format_with_rustfmt(variant_input)

        if variant_expected is None:
            errors.append((filepath, "rustfmt failed on variant"))
            variant_input = source
            variant_expected = formatted

        hidden_dir = HIDDEN_CASES_DIR / case_name
        hidden_dir.mkdir(parents=True, exist_ok=True)
        (hidden_dir / "input.rs").write_text(variant_input, encoding="utf-8")
        (hidden_dir / "expected_output.rs").write_text(variant_expected, encoding="utf-8")

        case_map[case_name] = {
            "source": filepath,
            "language": "rust",
        }

        if case_num % 25 == 0:
            print(f"    ... {case_num}/{TARGET_TOTAL} cases written")

    mapping_file = BASE_DIR / "tests" / "case_mapping.json"
    with open(mapping_file, "w") as f:
        json.dump(case_map, f, indent=2)

    print("\n" + "=" * 60)
    print("  Summary")
    print("=" * 60)
    print(f"  Total cases created:    {case_num}")
    print(f"  Variant errors:         {len(errors)}")
    print(f"  Original cases dir:     {ENV_CASES_DIR}")
    print(f"  Hidden cases dir:       {HIDDEN_CASES_DIR}")
    print(f"  Case mapping:           {mapping_file}")

    if errors:
        print(f"\n  Variant errors (fallback to original):")
        for fn, err in errors[:20]:
            print(f"    {fn}: {err}")

    print("\n" + "=" * 60)
    print("  Done!")
    print("=" * 60)
    return case_num


if __name__ == "__main__":
    num_cases = main()
    sys.exit(0 if num_cases > 0 else 1)
