#!/usr/bin/env python3
"""
Generate test cases for the Go code-formatter harbor task from gofmt output.

Creates:
- Original cases in environment/formatter/tests/cases/ (visible to agent)
- Variant cases in tests/hidden_cases/ (hidden, for verification only)

Hidden variants are generated by modifying string/number tokens in the
original input, then running gofmt on the variant to get expected output.
"""

import os
import sys
import re
import json
import subprocess
import shutil
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
ENV_CASES_DIR = BASE_DIR / "environment" / "formatter" / "tests" / "cases"
HIDDEN_CASES_DIR = BASE_DIR / "tests" / "hidden_cases"

TARGET_TOTAL = 200


def install_gofmt():
    """Ensure gofmt is available."""
    try:
        result = subprocess.run(
            ["gofmt", "--help"], capture_output=True, text=True,
        )
        print("  gofmt already available.")
    except FileNotFoundError:
        print("  ERROR: gofmt not found. Install Go first.")
        sys.exit(1)


def collect_go_files():
    """Collect Go source files from standard library and popular packages."""
    go_root = os.environ.get("GOROOT", "/usr/local/go")
    go_path = os.environ.get("GOPATH", os.path.expanduser("~/go"))

    candidates = []

    # Standard library
    std_dir = os.path.join(go_root, "src")
    if os.path.isdir(std_dir):
        for root, dirs, files in os.walk(std_dir):
            # Skip test files and vendor dirs
            dirs[:] = [d for d in dirs if d not in ("testdata", "vendor")]
            for f in files:
                if f.endswith(".go") and not f.endswith("_test.go"):
                    full = os.path.join(root, f)
                    size = os.path.getsize(full)
                    if 200 < size < 8000:
                        candidates.append(full)

    # Popular open-source Go projects (if available)
    extra_dirs = [
        os.path.join(go_path, "src"),
    ]
    for d in extra_dirs:
        if os.path.isdir(d):
            for root, dirs, files in os.walk(d):
                dirs[:] = [d for d in dirs if d not in ("testdata", "vendor", ".git")]
                for f in files:
                    if f.endswith(".go") and not f.endswith("_test.go"):
                        full = os.path.join(root, f)
                        size = os.path.getsize(full)
                        if 200 < size < 8000:
                            candidates.append(full)

    return candidates


def score_file(filepath):
    """Score a Go file by how interesting its formatting is."""
    try:
        with open(filepath, "r") as f:
            source = f.read()
    except (UnicodeDecodeError, IOError):
        return 0

    score = 0
    # Prefer files with diverse syntax
    patterns = [
        "func ", "type ", "struct {", "interface {", "go ", "select {",
        "switch ", "case ", "range ", "chan ", "<-", "defer ", "recover()",
        "panic(", "var ", "const ", ":=", "...", "[]", "map[", "if ",
        "for ", "return ", "import ", "package ", "/*", "//",
        "func(", "func (", "type ~", "any", "comparable",
    ]
    for p in patterns:
        if p in source:
            score += 2

    # Prefer moderate length
    length = len(source)
    if 500 < length < 3000:
        score += 20
    elif 200 <= length <= 500:
        score += 10
    elif 3000 <= length < 6000:
        score += 15

    return score


def format_with_gofmt(source):
    """Format Go source code with gofmt."""
    try:
        result = subprocess.run(
            ["gofmt"],
            input=source, capture_output=True, text=True, timeout=30,
        )
        if result.returncode == 0:
            return result.stdout
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass
    return None


def create_variant_input(source):
    """Create a variant of Go source by modifying strings, comments, numbers."""
    modified = source

    # Modify string literals
    modified = re.sub(
        r'(")((?:[^"\\]|\\.)*?)(")',
        lambda m: m.group(1) + m.group(2).replace("a", "e").replace("e", "i").replace("i", "o").replace("o", "u").replace("u", "a") + m.group(3),
        modified,
    )

    # Modify backtick strings
    def modify_backtick(m):
        content = m.group(1)
        if "`" not in content:
            return "`" + content.replace("a", "e").replace("e", "i").replace("i", "o") + "`"
        return m.group(0)

    modified = re.sub(r'`([^`]*)`', modify_backtick, modified)

    # Modify line comments
    PRESERVE_COMMENT = ("go:", "nolint", "TODO", "FIXME", "NOTE", "noescape", "norace")

    def modify_line_comment(m):
        prefix, text = m.group(1), m.group(2)
        if any(p in text for p in PRESERVE_COMMENT):
            return m.group(0)
        return prefix + text.replace("a", "e").replace("e", "i").replace("i", "o")

    modified = re.sub(r'(//\s?)(.*?)$', modify_line_comment, modified, flags=re.MULTILINE)

    # Modify integer literals
    def modify_integer(m):
        s = m.group(2)
        if s.startswith(('0x', '0X', '0o', '0O', '0b', '0B')):
            return m.group(0)
        try:
            if '.' in s or 'e' in s.lower():
                return m.group(0)
            return m.group(1) + str(int(s) + 7)
        except ValueError:
            return m.group(0)

    modified = re.sub(r'(\b)(\d+)\b', modify_integer, modified)

    if modified == source:
        modified = "// Variant test file\n" + source
    return modified


def main():
    print("=" * 60)
    print("  Go Code Formatter Test Case Generator")
    print("=" * 60)

    print("\nStep 1: Checking gofmt availability...")
    install_gofmt()

    print("\nStep 2: Collecting Go source files...")
    go_files = collect_go_files()
    print(f"  Found {len(go_files)} candidate files.")

    if len(go_files) < 50:
        print("  WARNING: Few Go files found. Results may be limited.")

    print("\nStep 3: Scoring and selecting files...")
    scored = [(score_file(f), f) for f in go_files]
    scored.sort(key=lambda x: x[0], reverse=True)
    selected_files = scored[:TARGET_TOTAL * 2]  # Get extra to filter

    print(f"\nStep 4: Generating test cases (target: {TARGET_TOTAL})...")
    if ENV_CASES_DIR.exists():
        shutil.rmtree(ENV_CASES_DIR)
    if HIDDEN_CASES_DIR.exists():
        shutil.rmtree(HIDDEN_CASES_DIR)
    ENV_CASES_DIR.mkdir(parents=True, exist_ok=True)
    HIDDEN_CASES_DIR.mkdir(parents=True, exist_ok=True)

    case_num = 0
    case_map = {}
    errors = []

    for score, filepath in selected_files:
        if case_num >= TARGET_TOTAL:
            break

        try:
            with open(filepath, "r") as f:
                source = f.read()
        except (UnicodeDecodeError, IOError):
            continue

        # Skip files that are already formatted (input == output)
        formatted = format_with_gofmt(source)
        if formatted is None:
            continue
        if source == formatted:
            # Still useful - tests idempotency
            pass

        case_num += 1
        case_name = f"case_{case_num:03d}"

        # Write original case
        case_dir = ENV_CASES_DIR / case_name
        case_dir.mkdir(parents=True, exist_ok=True)
        (case_dir / "input.go").write_text(source, encoding="utf-8")
        (case_dir / "expected_output.go").write_text(formatted, encoding="utf-8")

        # Generate hidden variant
        variant_input = create_variant_input(source)
        variant_expected = format_with_gofmt(variant_input)

        if variant_expected is None:
            variant_input = "// Variant test file\n" + source
            variant_expected = format_with_gofmt(variant_input)

        if variant_expected is None:
            errors.append((filepath, "gofmt failed on variant"))
            variant_input = source
            variant_expected = formatted

        hidden_dir = HIDDEN_CASES_DIR / case_name
        hidden_dir.mkdir(parents=True, exist_ok=True)
        (hidden_dir / "input.go").write_text(variant_input, encoding="utf-8")
        (hidden_dir / "expected_output.go").write_text(variant_expected, encoding="utf-8")

        case_map[case_name] = {
            "source": filepath,
            "language": "go",
        }

        if case_num % 25 == 0:
            print(f"    ... {case_num}/{TARGET_TOTAL} cases written")

    mapping_file = BASE_DIR / "tests" / "case_mapping.json"
    with open(mapping_file, "w") as f:
        json.dump(case_map, f, indent=2)

    print("\n" + "=" * 60)
    print("  Summary")
    print("=" * 60)
    print(f"  Total cases created:    {case_num}")
    print(f"  Variant errors:         {len(errors)}")
    print(f"  Original cases dir:     {ENV_CASES_DIR}")
    print(f"  Hidden cases dir:       {HIDDEN_CASES_DIR}")
    print(f"  Case mapping:           {mapping_file}")

    if errors:
        print(f"\n  Variant errors (fallback to original):")
        for fn, err in errors[:20]:
            print(f"    {fn}: {err}")

    print("\n" + "=" * 60)
    print("  Done!")
    print("=" * 60)
    return case_num


if __name__ == "__main__":
    num_cases = main()
    sys.exit(0 if num_cases > 0 else 1)
