#!/usr/bin/env python3
"""
Generate test cases for the Java code-formatter harbor task from google-java-format output.

Creates:
- Original cases in environment/formatter/tests/cases/ (visible to agent)
- Variant cases in tests/hidden_cases/ (hidden, for verification only)

Hidden variants are generated by modifying string/number tokens in the
original input, then running google-java-format on the variant to get expected output.
"""

import os
import sys
import re
import json
import subprocess
import shutil
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
ENV_CASES_DIR = BASE_DIR / "environment" / "formatter" / "tests" / "cases"
HIDDEN_CASES_DIR = BASE_DIR / "tests" / "hidden_cases"

TARGET_TOTAL = 200
GJF_JAR = "/usr/local/lib/google-java-format.jar"


def install_gjf():
    """Ensure google-java-format is available."""
    if os.path.exists(GJF_JAR):
        print(f"  google-java-format available at {GJF_JAR}")
        return

    print("  Downloading google-java-format...")
    os.makedirs(os.path.dirname(GJF_JAR), exist_ok=True)
    subprocess.run(
        ["wget", "-q",
         "https://github.com/google/google-java-format/releases/download/v1.19.2/google-java-format-1.19.2-all-deps.jar",
         "-O", GJF_JAR],
        check=True,
    )
    print("  google-java-format installed.")


def collect_java_files():
    """Collect Java source files from system."""
    candidates = []

    search_dirs = []

    # Look for Java source in common locations
    java_home = os.environ.get("JAVA_HOME", "/usr/lib/jvm")
    if os.path.isdir(java_home):
        for root, dirs, files in os.walk(java_home):
            dirs[:] = [d for d in dirs if d not in (".git", "test", "tests")]
            for f in files:
                if f.endswith(".java"):
                    full = os.path.join(root, f)
                    try:
                        size = os.path.getsize(full)
                        if 200 < size < 8000:
                            candidates.append(full)
                    except OSError:
                        pass

    # Look in Maven local repo
    m2_dir = os.path.expanduser("~/.m2/repository")
    if os.path.isdir(m2_dir):
        for root, dirs, files in os.walk(m2_dir):
            dirs[:] = [d for d in dirs if d not in (".git", "test", "tests")]
            for f in files:
                if f.endswith(".java") and "-sources.jar" not in f:
                    full = os.path.join(root, f)
                    try:
                        size = os.path.getsize(full)
                        if 200 < size < 8000:
                            candidates.append(full)
                    except OSError:
                        pass
                    if len(candidates) > 2000:
                        return candidates

    # Look in Gradle cache
    gradle_dir = os.path.expanduser("~/.gradle/caches")
    if os.path.isdir(gradle_dir):
        for root, dirs, files in os.walk(gradle_dir):
            dirs[:] = [d for d in dirs if d not in (".git", "test", "tests")]
            for f in files:
                if f.endswith(".java"):
                    full = os.path.join(root, f)
                    try:
                        size = os.path.getsize(full)
                        if 200 < size < 8000:
                            candidates.append(full)
                    except OSError:
                        pass
                    if len(candidates) > 3000:
                        return candidates

    return candidates


def score_file(filepath):
    """Score a Java file by how interesting its formatting is."""
    try:
        with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
            source = f.read()
    except (IOError):
        return 0

    score = 0
    patterns = [
        "class ", "interface ", "enum ", "record ", "sealed ",
        "public ", "private ", "protected ", "static ", "final ",
        "abstract ", "default ", "synchronized ", "volatile ", "transient ",
        "extends ", "implements ", "throws ", "new ",
        "if (", "else {", "for (", "while (", "switch (", "case ",
        "try (", "catch (", "finally {", "throw ",
        "return ", "import ", "package ",
        "@Override", "@Deprecated", "@FunctionalInterface",
        "List<", "Map<", "Set<", "Optional<", "Stream<",
        "->", "::", "...", "instanceof ",
        "/**", "/*", "//", "var ", "final var",
    ]
    for p in patterns:
        if p in source:
            score += 2

    # Prefer files with actual formatting issues
    lines = source.split("\n")
    long_lines = sum(1 for l in lines if len(l) > 100)
    if long_lines > 0:
        score += min(long_lines * 3, 15)

    length = len(source)
    if 500 < length < 3000:
        score += 20
    elif 200 <= length <= 500:
        score += 10
    elif 3000 <= length < 6000:
        score += 15

    return score


def format_with_gjf(source):
    """Format Java source code with google-java-format."""
    try:
        # Write to temp file
        tmpin = "/tmp/gjf_input_temp.java"
        with open(tmpin, "w") as f:
            f.write(source)

        result = subprocess.run(
            ["java", "-jar", GJF_JAR, "--aosp", tmpin],
            capture_output=True, text=True, timeout=30,
        )

        os.remove(tmpin)

        if result.returncode == 0:
            return result.stdout
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass
    return None


def create_variant_input(source):
    """Create a variant of Java source by modifying strings, comments, numbers."""
    modified = source

    # Modify string literals
    modified = re.sub(
        r'(")((?:[^"\\]|\\.)*?)(")',
        lambda m: m.group(1) + m.group(2).replace("a", "e").replace("e", "i").replace("i", "o").replace("o", "u").replace("u", "a") + m.group(3),
        modified,
    )

    # Modify text block strings (Java 13+)
    def modify_text_block(m):
        content = m.group(1)
        return '"""' + content.replace("a", "e").replace("e", "i").replace("i", "o") + '"""'

    modified = re.sub(r'"""(.*?)"""', modify_text_block, modified, flags=re.DOTALL)

    # Modify char literals
    modified = re.sub(
        r"(')((?:[^'\\]|\\.)*?)(')",
        lambda m: m.group(1) + m.group(2).replace("a", "e").replace("e", "i").replace("i", "o") + m.group(3),
        modified,
    )

    # Modify line comments
    PRESERVE_COMMENT = ("TODO", "FIXME", "NOTE", "noinspection", "noinspection", "CHECKSTYLE", "NOPMD")

    def modify_line_comment(m):
        prefix, text = m.group(1), m.group(2)
        if any(p in text for p in PRESERVE_COMMENT):
            return m.group(0)
        return prefix + text.replace("a", "e").replace("e", "i").replace("i", "o")

    modified = re.sub(r'(//\s?)(.*?)$', modify_line_comment, modified, flags=re.MULTILINE)

    # Modify integer literals
    def modify_integer(m):
        s = m.group(2)
        if s.startswith(('0x', '0X', '0o', '0O', '0b', '0B')):
            return m.group(0)
        try:
            if '.' in s or 'e' in s.lower():
                return m.group(0)
            # Handle Java long suffix
            clean = s.rstrip('lL')
            return m.group(1) + str(int(clean) + 7) + s[len(clean):]
        except ValueError:
            return m.group(0)

    modified = re.sub(r'(\b)(\d[\d_]*[lL]?)\b', modify_integer, modified)

    if modified == source:
        modified = "// Variant test file\n" + source
    return modified


def main():
    print("=" * 60)
    print("  Java Code Formatter Test Case Generator")
    print("=" * 60)

    print("\nStep 1: Checking google-java-format availability...")
    install_gjf()

    print("\nStep 2: Collecting Java source files...")
    java_files = collect_java_files()
    print(f"  Found {len(java_files)} candidate files.")

    if len(java_files) < 50:
        print("  WARNING: Few Java files found. Results may be limited.")

    print("\nStep 3: Scoring and selecting files...")
    scored = [(score_file(f), f) for f in java_files]
    scored.sort(key=lambda x: x[0], reverse=True)
    selected_files = scored[:TARGET_TOTAL * 2]

    print(f"\nStep 4: Generating test cases (target: {TARGET_TOTAL})...")
    if ENV_CASES_DIR.exists():
        shutil.rmtree(ENV_CASES_DIR)
    if HIDDEN_CASES_DIR.exists():
        shutil.rmtree(HIDDEN_CASES_DIR)
    ENV_CASES_DIR.mkdir(parents=True, exist_ok=True)
    HIDDEN_CASES_DIR.mkdir(parents=True, exist_ok=True)

    case_num = 0
    case_map = {}
    errors = []

    for score, filepath in selected_files:
        if case_num >= TARGET_TOTAL:
            break

        try:
            with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
                source = f.read()
        except (IOError):
            continue

        formatted = format_with_gjf(source)
        if formatted is None:
            continue

        case_num += 1
        case_name = f"case_{case_num:03d}"

        # Write original case
        case_dir = ENV_CASES_DIR / case_name
        case_dir.mkdir(parents=True, exist_ok=True)
        (case_dir / "input.java").write_text(source, encoding="utf-8")
        (case_dir / "expected_output.java").write_text(formatted, encoding="utf-8")

        # Generate hidden variant
        variant_input = create_variant_input(source)
        variant_expected = format_with_gjf(variant_input)

        if variant_expected is None:
            variant_input = "// Variant test file\n" + source
            variant_expected = format_with_gjf(variant_input)

        if variant_expected is None:
            errors.append((filepath, "google-java-format failed on variant"))
            variant_input = source
            variant_expected = formatted

        hidden_dir = HIDDEN_CASES_DIR / case_name
        hidden_dir.mkdir(parents=True, exist_ok=True)
        (hidden_dir / "input.java").write_text(variant_input, encoding="utf-8")
        (hidden_dir / "expected_output.java").write_text(variant_expected, encoding="utf-8")

        case_map[case_name] = {
            "source": filepath,
            "language": "java",
        }

        if case_num % 25 == 0:
            print(f"    ... {case_num}/{TARGET_TOTAL} cases written")

    mapping_file = BASE_DIR / "tests" / "case_mapping.json"
    with open(mapping_file, "w") as f:
        json.dump(case_map, f, indent=2)

    print("\n" + "=" * 60)
    print("  Summary")
    print("=" * 60)
    print(f"  Total cases created:    {case_num}")
    print(f"  Variant errors:         {len(errors)}")
    print(f"  Original cases dir:     {ENV_CASES_DIR}")
    print(f"  Hidden cases dir:       {HIDDEN_CASES_DIR}")
    print(f"  Case mapping:           {mapping_file}")

    if errors:
        print(f"\n  Variant errors (fallback to original):")
        for fn, err in errors[:20]:
            print(f"    {fn}: {err}")

    print("\n" + "=" * 60)
    print("  Done!")
    print("=" * 60)
    return case_num


if __name__ == "__main__":
    num_cases = main()
    sys.exit(0 if num_cases > 0 else 1)
